name: lss_single_multiclass
root_dir: external_paths/data_root
validate_dir: external_paths/test_data_root
test_dir: external_paths/test_data_root

yaml_parser: load_lift_splat_shoot_params
extrinsic: 2

train_params:
  batch_size: 1
  epoches: 5
  eval_freq: 1
  max_cav: 5
  save_freq: 1

input_source: ['camera']
label_type: 'camera'

comm_range: 70

add_data_extension: ['bev_visibility.png']

fusion:
  args: 
    proj_first: false # useless
    grid_conf: &grid_conf
      xbound: [-36, 36, 0.125]   # 限制x方向的范围并划分网格
      ybound: [-12, 12, 0.125]   # 限制y方向的范围并划分网格
      zbound: [-22, 14, 36.0]   # 限制z方向的范围并划分网格
      ddiscr: [2, 50, 48]
      mode: 'LID'
    data_aug_conf: &data_aug_conf
      resize_lim: [0.8, 0.85]
      final_dim: [480, 640]
      rot_lim: [-3.6, 3.6]
      H: 600
      W: 800
      rand_flip: False
      bot_pct_lim: [0.0, 0.05]
      cams: ['camera0', 'camera1', 'camera2', 'camera3']
      Ncams: 4
  core_method: 'latemulticlass'
  dataset: v2xverse

preprocess:
  core_method: SpVoxelPreprocessor
  args:
    max_points_per_voxel: 32
    max_voxel_test: 70000
    max_voxel_train: 32000
    voxel_size: &voxel_size [0.125, 0.125, 36]
  cav_lidar_range: &lidar_range [-36, -12, -22, 36, 12, 14]

data_augment:
- ALONG_AXIS_LIST:
  - x
  NAME: random_world_flip
- NAME: random_world_rotation
  WORLD_ROT_ANGLE: [-0.78539816, 0.78539816]
- NAME: random_world_scaling
  WORLD_SCALE_RANGE: [0.95, 1.05]

postprocess:
  core_method: VoxelPostprocessor
  anchor_args:
    D: 1
    H: 192
    W: 576
    cav_lidar_range: *lidar_range
    feature_stride: 2
    h: 1.56
    l: 3.9
    num: &achor_num 1
    r: &anchor_yaw [0]
    vd: 36
    vh: 0.125
    vw: 0.125
    w: 1.6
  dir_args: &dir_args
    anchor_yaw: *anchor_yaw
    dir_offset: 0.7853
    num_bins: 1
  gt_range: *lidar_range
  max_num: 100
  nms_thresh: 0.15
  order: hwl
  target_args:
    neg_threshold: 0.45
    pos_threshold: 0.6
    score_threshold: 0.2

model:
  core_method: lift_splat_shoot_multiclass
  args:
    multi_class: true
    anchor_number: 3
    grid_conf: *grid_conf
    data_aug_conf: *data_aug_conf
    dir_args: *dir_args
    img_downsample: 8
    img_features: 128
    use_depth_gt: false
    depth_supervision: false
    bevout_feature: 128

    shrink_header:
      kernal_size: [ 3 ]
      stride: [ 2 ]
      padding: [ 1 ]
      dim: [ 128 ]
      input_dim: 128
    camera_encoder: EfficientNet

loss:
  core_method: center_point_loss_multiclass
  args:
    cls_weight: 5.0
    code_weights: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 5.0, 5.0]
    loc_weight: 1.0
    target_assigner_config:
      box_coder: ResidualCoder
      cav_lidar_range: *lidar_range
      gaussian_overlap: 0.1
      max_objs: 40
      min_radius: 2
      out_size_factor: 2
      voxel_size: *voxel_size
  # args:
  #   pos_cls_weight: 1.0
  #   cls:
  #     type: 'SigmoidFocalLoss'
  #     alpha: 0.25
  #     gamma: 2.0
  #     weight: 1.0
  #   reg:
  #     type: 'WeightedSmoothL1Loss'
  #     sigma: 3.0
  #     codewise: true
  #     weight: 2.0

optimizer:
  args:
    eps: 1.0e-10
    weight_decay: 1e-4
  core_method: Adam
  lr: 0.002

lr_scheduler:
  core_method: multistep
  gamma: 0.1
  step_size:
  - 2
  - 4
